// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoriaAgentes.Data;

#nullable disable

namespace MonitoriaAgentes.Migrations
{
    [DbContext(typeof(MonitoriaAgentesContext))]
    partial class MonitoriaAgentesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MonitoriaAgentes.Models.Monitoria", b =>
                {
                    b.Property<int>("MonitoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonitoriaId"), 1L, 1);

                    b.Property<string>("AD_Agente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Assunto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDaMonitoria")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MatriculaAgente")
                        .HasColumnType("float");

                    b.Property<string>("NomeAgente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonitoriaId");

                    b.ToTable("Monitoria");
                });
#pragma warning restore 612, 618
        }
    }
}
